# This file was generated by GoReleaser. DO NOT EDIT.
cask "olk" do
  version "0.9.5"

  on_macos do
    on_intel do
      sha256 "bf056d596d9b209d26fc310d6e07da6c4057d12a9c2307033c75e15d23ff4290"
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "463140e3d12725ce8ad04a1038e75215c1d4f3a229746d610171bb2c1bb7e9e5"
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "olk"
  desc "CLI for Microsoft Outlook via Microsoft Graph API"
  homepage "https://github.com/rlrghb/olkcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/olk"]
    end
  end

  # No zap stanza required

end
