# This file was generated by GoReleaser. DO NOT EDIT.
cask "olk" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_amd64.tar.gz"
      sha256 "027205fa141648614f5421609156bc41093074afab7a808f779408f148a80fb2"
    end
    on_arm do
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_arm64.tar.gz"
      sha256 "b6fbc5f29131e6f2881676c224fca586931f1ee4c70968629f3fa9ced4d616fd"
    end
  end

  name "olk"
  desc "CLI for Microsoft Outlook via Microsoft Graph API"
  homepage "https://github.com/rlrghb/olkcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olk"

  # No zap stanza required

end
