# This file was generated by GoReleaser. DO NOT EDIT.
cask "olk" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "6f2c3656975c2c7df85c8af8f780b8d150a756b6e1fd12503cd0df7274ab2f31"
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "586c38e6a45e31e2eba518aa74ca92d71ff020223e14ed8c7d56dc21d582081d"
      url "https://github.com/rlrghb/olkcli/releases/download/v#{version}/olk_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "olk"
  desc "CLI for Microsoft Outlook via Microsoft Graph API"
  homepage "https://github.com/rlrghb/olkcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olk"

  # No zap stanza required

end
